name: Build  Java App

on:
  push:
    branches:
      - -main  # Trigger on pushes to the main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java environment
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'  # Adjust to your version
        distribution: 'temurin'

    # Step 3: Build the application
    - name: Build with Maven
      run: mvn clean package 
